//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marafi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMB
    {
        public int ID_employee { get; set; }
        public string name_emp { get; set; }
        public Nullable<int> balance_vacations { get; set; }
        public Nullable<int> consumer { get; set; }
        public Nullable<int> reminder { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<int> account_number { get; set; }
        public string Duration_emp { get; set; }
    }
}
