//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marafi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class follow_deliver
    {
        public int Id_charging { get; set; }
        public string name_chg { get; set; }
        public string quantity_charg { get; set; }
        public string type_charging { get; set; }
        public string coming_from { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string sender { get; set; }
        public string recip { get; set; }
    }
}
