//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marafi1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class marafiEntities1 : DbContext
    {
        public marafiEntities1()
            : base("name=marafiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<charging> charging { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<content> content { get; set; }
        public virtual DbSet<EMB> EMB { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<follow_deliver> follow_deliver { get; set; }
        public virtual DbSet<@new> @new { get; set; }
        public virtual DbSet<shipment> shipment { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
