//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marafi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipment
    {
        public int ID_ship { get; set; }
        public string name_recip { get; set; }
        public Nullable<int> phone_recip { get; set; }
        public string city_address { get; set; }
        public string region { get; set; }
        public string shipment_cont { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> ship_price { get; set; }
        public Nullable<int> ID_man { get; set; }
        public Nullable<int> ID_charging { get; set; }
    
        public virtual charging charging { get; set; }
        public virtual clients clients { get; set; }
    }
}
